import { NextResponse } from "next/server";

type ReqBody = {
  prompt?: string;
  model?: string;
};

export async function POST(req: Request) {
  try {
    const { prompt = "", model = "openrouter/auto" } = (await req.json()) as ReqBody;

    if (!prompt || prompt.trim().length < 8) {
      return NextResponse.json({ error: "Prompt is required" }, { status: 400 });
    }

    const apiKey = process.env.OPENROUTER_API_KEY;

    // Fallback local generator if no API key configured
    if (!apiKey) {
      const stub = buildStubFromPrompt(prompt);
      return NextResponse.json({ source: "stub", mcp: stub });
    }

    // Call OpenRouter chat completions
    const res = await fetch("https://openrouter.ai/api/v1/chat/completions", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        Authorization: `Bearer ${apiKey}`,
      },
      body: JSON.stringify({
        model,
        messages: [
          {
            role: "system",
            content:
              "You are an assistant that generates Model Context Protocol (MCP) server definitions. Always return strictly-formatted JSON with keys: name, description, category (Development|Database|Communication|Productivity|Cloud), tags (array of strings), author, size (like '2.3 MB'), installCommand (single-line command to install or run the MCP). Do not include markdown or code fences.",
          },
          {
            role: "user",
            content: `Create an MCP based on this request: ${prompt}. Return JSON only.`,
          },
        ],
        temperature: 0.2,
      }),
      // Ensure Edge compatibility
      cache: "no-store",
    });

    if (!res.ok) {
      const text = await res.text();
      console.error("OpenRouter error:", text);
      const stub = buildStubFromPrompt(prompt);
      return NextResponse.json({ source: "stub", mcp: stub, warning: "OpenRouter call failed; returned stub" }, { status: 200 });
    }

    const data = await res.json();
    const content: string = data?.choices?.[0]?.message?.content ?? "{}";

    let parsed: any;
    try {
      parsed = JSON.parse(content);
    } catch {
      // Attempt to extract JSON block
      const match = content.match(/\{[\s\S]*\}/);
      if (match) {
        parsed = JSON.parse(match[0]);
      }
    }

    if (!parsed || typeof parsed !== "object" || !parsed.name) {
      const stub = buildStubFromPrompt(prompt);
      return NextResponse.json({ source: "fallback", mcp: stub }, { status: 200 });
    }

    return NextResponse.json({ source: "openrouter", mcp: normalizeMCP(parsed) });
  } catch (e) {
    console.error("/api/creator error", e);
    return NextResponse.json({ error: "Unexpected error" }, { status: 500 });
  }
}

function normalizeMCP(obj: any) {
  const name = String(obj.name ?? "Custom MCP");
  return {
    id: Date.now(),
    name,
    description: String(obj.description ?? "Generated by AI MCP Creator"),
    rating: 5.0,
    downloads: "0",
    category: String(obj.category ?? "Development"),
    tags: Array.isArray(obj.tags) ? obj.tags.map(String) : [],
    verified: false,
    author: String(obj.author ?? "AI Creator"),
    lastUpdated: "just now",
    size: String(obj.size ?? "1.0 MB"),
    installCommand: String(obj.installCommand ?? "echo \"Install steps go here\"")
  };
}

function buildStubFromPrompt(prompt: string) {
  const p = prompt.toLowerCase();
  if (p.includes("github")) {
    return normalizeMCP({
      name: "GitHub Helper",
      description: "Manage issues, PRs, and repos via MCP.",
      category: "Development",
      tags: ["github", "issues", "pull requests"],
      installCommand: "npm install -g github-helper-mcp",
      size: "2.2 MB",
    });
  }
  if (p.includes("database") || p.includes("sql") || p.includes("postgres")) {
    return normalizeMCP({
      name: "Database Helper",
      description: "Query and manage databases with natural language.",
      category: "Database",
      tags: ["sql", "postgres", "mysql"],
      installCommand: "pip install database-helper-mcp",
      size: "3.1 MB",
    });
  }
  if (p.includes("slack") || p.includes("chat")) {
    return normalizeMCP({
      name: "Slack Connector",
      description: "Send messages and manage channels via MCP.",
      category: "Communication",
      tags: ["slack", "chat", "bot"],
      installCommand: "curl -sSL https://install.slack-connector-mcp.com | bash",
      size: "1.8 MB",
    });
  }
  return normalizeMCP({
    name: "Custom MCP",
    description: "Generated from your prompt.",
    category: "Productivity",
    tags: ["custom"],
    installCommand: "echo \"Add install steps here\"",
    size: "1.0 MB",
  });
}

