export type DocCategory = 'cli' | 'ide' | 'deploy' | 'testing';

export type DocEntry = {
  slug: string;
  path: string;
  title: string;
  description: string;
  category: DocCategory;
  updatedAt: string;
  readingTimeMinutes: number;
  version: string;
  tags: string[];
  breadcrumbs?: string[];
};

export const DOCS: DocEntry[] = [
  {
    slug: 'codex-cli-installation',
    path: '/docs/codex-cli-installation',
    title: 'How to Install and Use MCPs with Codex CLI',
    description: 'Complete guide to installing and configuring MCP servers with Codex CLI for AI-powered development.',
    category: 'cli',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['codex', 'openai', 'cli', 'installation', 'setup'],
    breadcrumbs: ['Codex CLI', 'Installation Guide'],
  },
  {
    slug: 'gemini-cli-setup',
    path: '/docs/gemini-cli-setup',
    title: 'Getting Started with MCPs in Gemini CLI',
    description: 'Step-by-step setup guide for integrating Model Context Protocol servers with Gemini CLI.',
    category: 'cli',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['gemini', 'google', 'cli', 'setup'],
    breadcrumbs: ['Gemini CLI', 'Setup Guide'],
  },
  {
    slug: 'claude-cli',
    path: '/docs/claude-cli',
    title: 'Running MCPs with Claude CLI (Examples + Troubleshooting)',
    description: 'Learn to run MCP servers with Claude CLI, including practical examples and common troubleshooting solutions.',
    category: 'cli',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['claude', 'anthropic', 'cli', 'troubleshooting'],
    breadcrumbs: ['Claude CLI', 'Examples & Troubleshooting'],
  },
  {
    slug: 'terminal-cli',
    path: '/docs/terminal-cli',
    title: 'Using MCPs in Terminal (Universal CLI Setup)',
    description: 'Universal guide for setting up and using MCP servers in any terminal environment.',
    category: 'cli',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['terminal', 'shell', 'cli', 'universal'],
    breadcrumbs: ['Universal Terminal', 'Setup Guide'],
  },
  {
    slug: 'cursor-setup',
    path: '/docs/cursor-setup',
    title: 'How to Install and Use MCPs in Cursor IDE',
    description: 'Complete setup guide for connecting and running MCP servers from Cursor IDE with troubleshooting tips.',
    category: 'ide',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 6,
    version: 'MCP SDK v2.1.0',
    tags: ['cursor', 'ide', 'ai', 'setup'],
    breadcrumbs: ['Cursor', 'Setup Guide'],
  },
  {
    slug: 'windsurf-setup',
    path: '/docs/windsurf-setup',
    title: 'Running MCPs in Windsurf IDE',
    description: 'Step-by-step guide to configure and use Model Context Protocol servers in Windsurf IDE.',
    category: 'ide',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 5,
    version: 'MCP SDK v2.1.0',
    tags: ['windsurf', 'ide', 'codeium', 'setup'],
    breadcrumbs: ['Windsurf', 'Configuration'],
  },
  {
    slug: 'vscode-integration',
    path: '/docs/vscode-integration',
    title: 'MCPs in VSCode - Complete Setup Guide',
    description: 'Comprehensive guide for integrating MCP servers with Visual Studio Code for enhanced AI development.',
    category: 'ide',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['vscode', 'visual studio code', 'integration', 'extension'],
    breadcrumbs: ['VS Code', 'Integration Guide'],
  },
  {
    slug: 'jetbrains-integration',
    path: '/docs/jetbrains-integration',
    title: 'MCP Setup in JetBrains IDEs (PyCharm, IntelliJ, WebStorm)',
    description: 'Configure Model Context Protocol servers in JetBrains IDEs including PyCharm, IntelliJ IDEA, and WebStorm.',
    category: 'ide',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 5,
    version: 'MCP SDK v2.1.0',
    tags: ['jetbrains', 'pycharm', 'intellij', 'webstorm', 'integration'],
    breadcrumbs: ['JetBrains', 'MCP Integration'],
  },
  {
    slug: 'claude-desktop',
    path: '/docs/claude-desktop',
    title: 'Connecting MCPs in Claude Desktop (Mac & Windows)',
    description: 'Complete guide to connecting and managing MCP servers in Claude Desktop for Mac and Windows.',
    category: 'ide',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 5,
    version: 'MCP SDK v2.1.0',
    tags: ['claude', 'desktop', 'mac', 'windows', 'setup'],
    breadcrumbs: ['Claude Desktop', 'Connection Guide'],
  },
  {
    slug: 'docker-deployment',
    path: '/docs/docker-deployment',
    title: 'Running MCP Servers in Docker',
    description: 'Deploy and manage MCP servers using Docker containers with security best practices and examples.',
    category: 'deploy',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['docker', 'containers', 'deployment', 'ops'],
    breadcrumbs: ['Docker', 'Runtime Guide'],
  },
  {
    slug: 'kubernetes',
    path: '/docs/kubernetes',
    title: 'Deploying MCP Servers on Kubernetes Clusters',
    description: 'Scale MCP servers on Kubernetes with deployment manifests, service discovery, and monitoring.',
    category: 'deploy',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['kubernetes', 'k8s', 'deployment', 'clusters'],
    breadcrumbs: ['Kubernetes', 'Cluster Deployment'],
  },
  {
    slug: 'vercel-deployment',
    path: '/docs/vercel-deployment',
    title: 'Serverless MCP Deployment on Vercel',
    description: 'Deploy MCP servers as serverless functions on Vercel with edge computing and global distribution.',
    category: 'deploy',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['vercel', 'serverless', 'edge', 'deployment'],
    breadcrumbs: ['Vercel', 'Serverless Deployment'],
  },
  {
    slug: 'aws-lambda',
    path: '/docs/aws-lambda',
    title: 'Deploying MCPs on AWS Lambda',
    description: 'Run MCP servers on AWS Lambda with API Gateway integration and cost-effective scaling.',
    category: 'deploy',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['aws', 'lambda', 'serverless', 'deployment'],
    breadcrumbs: ['AWS Lambda', 'Function Guide'],
  },
  {
    slug: 'github-actions',
    path: '/docs/github-actions',
    title: 'Automating MCP Workflows with GitHub Actions',
    description: 'Automate MCP server deployment, testing, and distribution using GitHub Actions CI/CD pipelines.',
    category: 'deploy',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 5,
    version: 'MCP SDK v2.1.0',
    tags: ['github', 'actions', 'ci', 'cd', 'automation'],
    breadcrumbs: ['GitHub Actions', 'Automation Guide'],
  },
  {
    slug: 'remote-mcp',
    path: '/docs/remote-mcp',
    title: 'Connecting to Remote MCP Servers',
    description: 'Configure and connect to remote MCP servers with authentication, security, and network considerations.',
    category: 'deploy',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 5,
    version: 'MCP SDK v2.1.0',
    tags: ['remote', 'network', 'security', 'connectivity'],
    breadcrumbs: ['Remote MCP', 'Connectivity Guide'],
  },
  {
    slug: 'testing-mcp',
    path: '/docs/testing-mcp',
    title: 'Debugging & Testing MCPs with MCP Inspector',
    description: 'Debug and test MCP servers using MCP Inspector and other debugging tools for reliable development.',
    category: 'testing',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 3,
    version: 'MCP SDK v2.1.0',
    tags: ['testing', 'inspector', 'debug'],
    breadcrumbs: ['MCP Inspector', 'Debugging Guide'],
  },
  {
    slug: 'common-errors',
    path: '/docs/common-errors',
    title: '10 Most Common MCP Setup Errors (and Fixes)',
    description: 'Troubleshoot the most common MCP setup errors with step-by-step solutions and prevention tips.',
    category: 'testing',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 5,
    version: 'MCP SDK v2.1.0',
    tags: ['errors', 'setup', 'troubleshooting'],
    breadcrumbs: ['Setup Errors', 'Fixes'],
  },
  {
    slug: 'connection-refused',
    path: '/docs/connection-refused',
    title: 'Fixing MCP Server Connection Refused',
    description: 'Resolve MCP server connection refused errors with network, firewall, and configuration troubleshooting.',
    category: 'testing',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 3,
    version: 'MCP SDK v2.1.0',
    tags: ['network', 'connection', 'firewall'],
    breadcrumbs: ['Networking', 'Connection Refused'],
  },
  {
    slug: 'authentication-errors',
    path: '/docs/authentication-errors',
    title: 'MCP Authentication & API Key Fixes',
    description: 'Fix MCP authentication issues, API key problems, and permission errors with detailed solutions.',
    category: 'testing',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['authentication', 'api keys', 'security'],
    breadcrumbs: ['Authentication', 'API Keys'],
  },
  {
    slug: 'deployment-errors',
    path: '/docs/deployment-errors',
    title: 'Fixing MCP Deployment Issues in Docker/Vercel',
    description: 'Troubleshoot MCP deployment problems in Docker containers and Vercel serverless environments.',
    category: 'testing',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['deployment', 'docker', 'vercel', 'errors'],
    breadcrumbs: ['Deployment', 'Error Handling'],
  },
  {
    slug: 'mcp-not-showing',
    path: '/docs/mcp-not-showing',
    title: `Why MCPs Don't Show Up in Claude Desktop`,
    description: 'Diagnose and fix issues when MCP servers are not appearing or working in Claude Desktop application.',
    category: 'testing',
    updatedAt: '2025-09-21T00:00:00.000Z',
    readingTimeMinutes: 4,
    version: 'MCP SDK v2.1.0',
    tags: ['claude', 'desktop', 'visibility', 'troubleshooting'],
    breadcrumbs: ['Claude Desktop', 'Visibility Issues'],
  },
]

export const CATEGORY_LABELS = {
  cli: 'CLI Tools',
  ide: 'IDEs',
  deploy: 'Deployment & Ops',
  testing: 'Testing & Debugging',
} as const;

export function getDocsByCategory() {
  return DOCS.reduce((acc, doc) => {
    if (!acc[doc.category]) {
      acc[doc.category] = [];
    }
    acc[doc.category].push(doc);
    return acc;
  }, {} as Record<DocCategory, DocEntry[]>);
}

export function getDocBySlug(slug: string) {
  return DOCS.find(doc => doc.slug === slug);
}
